import os
import random
import uuid
import streamlit as st
import pandas as pd
from datetime import datetime

st.set_page_config(page_title="Can AI Dream of Unseen Galaxies?", layout="centered")

st.title("Can AI Dream of Unseen Galaxies?")
st.subheader("Conditional Diffusion Model for Galaxy Morphology Augmentation")
st.markdown("**Chenrui Ma, Zechang Sun, Tao Jing**  \nTsinghua University")

# Sidebar navigation
tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs(["🔭 Intro", "🧠 Method", "🌌 Generation", "🚀 Application", "📚 Citation", "📝 Quiz"])

st.markdown("---")

# Tab content
with tab1:
    st.header("🔭 Introduction")
    st.markdown("""
    Machine learning is transforming astronomy, but its effectiveness is often limited by scarce labeled data—especially for rare objects. We propose a conditional diffusion model that generates realistic galaxy images based on specified visual features, using the Galaxy Zoo 2 dataset for training.
    These synthetic images help ML models better generalize, improving classification accuracy and significantly boosting rare object detection. For example, our approach doubled the detection of dust lane galaxies compared to traditional methods. This work shows how generative models can act as “world simulators”, bridging gaps in data and enabling new discoveries in observational astronomy.
 
    **Key Contributions**:
    - A conditional galaxy image generation model based on morphological prompts.
    - Applications to data augmentation and rare galaxy synthesis.
    - Newly found early-type dust lane catalog by classifier trained on augmented data.
    """)
    
with tab2:
    st.header("🧠 Method")
    st.image("assets/schema.png", caption="Schematic diagram of our model and downstream tasks.", use_container_width=True)
    st.markdown("""
    We use diffusion models to generate high-quality galaxy images based on morphological descriptions. These models work by gradually transforming random noise into realistic images through a learned denoising process.

    We fine-tuned the pretrained Stable Diffusion v1.5 model using galaxy images and their corresponding morphological labels from the [Galaxy Zoo 2 (GZ2)](https://data.galaxyzoo.org) dataset. This allows the model to learn how different visual features relate to specific galaxy types.

    During inference, we observed that using text-only conditioning often leads to systematically over-bright images, due to singularities in the diffusion process at the final denoising step. To mitigate this, we introduce randomly selected reference images as control and begin the denoising process from their noised versions. This helps regulate brightness while preserving visual fidelity.

    After training, the model learns the mapping between morphology and visual features, allowing it to act as a “world simulator.” It can generate both realistic and hypothetical galaxies, including rare or unseen combinations such as early-type galaxies with star-forming traits. These synthetic images can enrich downstream model training and support new scientific discoveries.
    """)

with tab3:
    st.header("🌌 Generation Examples")
    st.markdown("Below are examples of generated galaxies conditioned on different morphological features. " \
    "The annotated capital letters represents prompts used to generate simulated galaxies as [Morphological Prompt Legend](#morph-table) table shows.")
    
    st.markdown('<a name="summary"></a>', unsafe_allow_html=True)
    st.image("assets/summary_sdss.png", caption="Comparison of real galaxy images drom SDSS and those generated by our model under various morphology-related text prompts.", use_container_width=True)

    st.markdown('<a name="morph-table"></a>', unsafe_allow_html=True)
    st.markdown("### 🔠 Morphological Prompt Legend")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("""
        | Type | Prompt                                |
        |------|----------------------------------------|
        | A    | cigar-shaped galaxy                   |
        | B    | completely round galaxy               |
        | C    | edge-on galaxy                        |
        | D    | in-between round galaxy              |
        | E    | ring galaxy                           |
        | F    | spiral galaxy with 4 spiral arms     |
        | G    | spiral galaxy with loosely wound 2 arms |
        | H    | spiral galaxy with tightly wound arms |
        | I    | spiral galaxy with just noticeable bulge    |
        """)

    with col2:
        st.markdown("""
        | Type | Prompt                                      |
        |------|----------------------------------------------|
        | J    | spiral galaxy with obvious bulge            |
        | K    | in-between round galaxy, {dust lane:1.3}    |
        | L    | edge-on galaxy, {dust lane:1.3}, with rounded edge-on bulge     |
        | M    | bar-shaped structure in the galaxy center   |
        | N    | edge-on galaxy with rounded bulge           |
        | O    | in-between round galaxy, merger             |
        | P    | spiral galaxy, just noticeable bulge, merger|
        """)
    
    st.markdown("**Want to generate galaxy yourself? [ 👉 GitHub Repo](https://github.com/repo)**")
    

with tab4:
    st.header("🚀 Applications")
    st.markdown("""
    - **Data Synthesis**: generate realistic and scientific galaxy images given morphological descriptions, especially for rare galaxy types. 
                For example, generate rare realistic early-type dust lane galaxies (D-ETGs) by merging features from early-type galaxies and disky galaxies with dust lane, as shown of the functions of the world simulator.
    """)
    st.image("assets/diagram_D-ETG.png", caption="Generative extrapolation of early-type galaxies with prominent dust lanes (D-ETGs).", use_container_width=True)
    
    st.markdown("""
    - **Enhacing galaxy classifiers**: Improve galaxy morphology classification especially few-shot learning with synthetic data by our model, outperforming baseline and most focal loss case in purity, completeness and F1-score. 
    - **Boosting rare galaxy detection**: The classifier trained on our augmented data can detect positive classes more effectively in GZ. For example, we successfully newly identified 467 missclassified D-ETGs from 239,695 GZ-SDSS dataset and contribute a D-ETG catalog for interested readers.
    """)
    st.image("assets/summary_D-ETG.png", caption="Examples of D-ETGs synthesized by our diffusion model (upper panel) and newly identified instances using machine learning models augmented with the synthesized data (lower panel).", use_container_width=True)
    
    
with tab5:
    st.header("📚 Citation")
    st.code("""
@inproceedings{ma2025can,
  title     = {Can AI Dream of Unseen Galaxies? Conditional Diffusion Model for Galaxy Morphology Augmentation},
  author    = {Chenrui Ma, Zechang Sun, Tao Jing et al.},
  booktitle = {ApJS},
  year      = {2025}
}
    """, language="bibtex")
    st.markdown("Feel free to contact us for collaboration!")
    st.markdown("📧 **Contact:** mcr24, szc22, jingt20 [@mails.tsinghua.edu.cn]")

with tab6:
    st.header("📝 Real vs Generated: Quiz Time!")
    col_text, col_button = st.columns([6, 1])
    with col_text:  
        st.markdown("Can you tell which galaxies are real and which are generated? Try the quiz below!\nThere are 8 real galaxies by observation and 2 generated galaxies.")
    with col_button:
        restart = st.button("🔄", help="Restart Quiz")
        if restart:
            st.session_state.pop("quiz_images", None)

    # Initialize image list only once
    if "quiz_images" not in st.session_state:
        gen_dir = "assets/generated"
        real_dir = "assets/sdss"
        gen_images = random.sample(os.listdir(gen_dir), 2)
        real_images = random.sample(os.listdir(real_dir), 8)
        image_data = [{"file": os.path.join(gen_dir, img), "label": "Generated"} for img in gen_images] + \
                     [{"file": os.path.join(real_dir, img), "label": "Real"} for img in real_images]
        random.shuffle(image_data)
        st.session_state.quiz_images = image_data  # 缓存图片

    image_data = st.session_state.quiz_images

    # UI for quiz
    user_answers = {}
    st.markdown("### 🔍 Select your answers:")
    for idx, item in enumerate(image_data):
        col1, col2 = st.columns([1, 3])
        with col1:
            st.image(item["file"], width=100)
        with col2:
            user_answers[idx] = st.radio(f"Image {idx+1}", ["Real", "Generated"], key=f"img_{idx}")

    username = st.text_input("Your name or ID", value="anonymous")

    if st.button("Submit Answers"):
        total = len(image_data)
        correct = 0
        results = []
        for idx, item in enumerate(image_data):
            is_correct = (user_answers[idx] == item["label"])
            correct += int(is_correct)
            results.append({
                "username": username,
                "timestamp": datetime.now().isoformat(),
                "image": os.path.basename(item["file"]),
                "truth": item["label"],
                "answer": user_answers[idx],
                "correct": is_correct
            })

        # Save result
        result_df = pd.DataFrame(results)
        os.makedirs("quiz_data", exist_ok=True)
        result_file = f"quiz_data/result_{uuid.uuid4().hex[:8]}.csv"
        result_df.to_csv(result_file, index=False)

        st.success(f"You got {correct}/{total} correct!")

        # Update leaderboard
        leaderboard = []
        for file in os.listdir("quiz_data"):
            if file.endswith(".csv"):
                df = pd.read_csv(os.path.join("quiz_data", file))
                score = df["correct"].sum()
                total_q = len(df)
                name = df["username"].iloc[0]
                leaderboard.append((name, score, total_q))

        leaderboard_df = pd.DataFrame(leaderboard, columns=["Name", "Score", "Total"])
        leaderboard_df["Accuracy"] = leaderboard_df["Score"] / leaderboard_df["Total"]
        leaderboard_df = leaderboard_df.sort_values(by="Accuracy", ascending=False).reset_index(drop=True)

        st.markdown("### 🏆 Leaderboard (Top 10)")
        st.dataframe(leaderboard_df.head(10))
